# Generated by Django 3.0 on 2022-01-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
