# Generated by Django 3.0 on 2022-01-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0002_auto_20220105_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ons', to='marvel.Team'),
        ),
    ]
