# Generated by Django 4.0.1 on 2022-01-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandnames_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Brand',
        ),
    ]
